name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 black isort
    
    - name: Run linting
      run: |
        flake8 src/ --max-line-length=88 --extend-ignore=E203,W503
        black --check src/
        isort --check-only src/
    
    - name: Run tests
      run: |
        pytest tests/ --cov=src/ --cov-report=xml --cov-report=term
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TINKOFF_TOKEN: ${{ secrets.TINKOFF_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Security check
      run: |
        echo "Checking for secrets in code..."
        ! grep -r "sk-" src/ || exit 1
        ! grep -r "bot.*:" src/ || exit 1
        echo "Security check passed!"
